# Generated by Django 5.0.1 on 2024-02-27 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_product_orderitem_product_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='created',
            new_name='created_at',
        ),
    ]
