# Generated by Django 5.0.1 on 2024-03-13 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_category_m_description_and_more'),
        ('myapp', '0007_rename_created_category_created_at'),
    ]

    operations = [
    ]
